project:
  type: website
  output-dir: docs

website:
  site-url: https://github.com/spiritofchaoss/spiritofchaoss.github.io
  google-analytics: 
    tracking-id: ""
    anonymize-ip: true
  navbar:
    title: false
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - text: get in touch!
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/jason-cheung-3vb/
            target: _blank
          - icon: envelope
            text: Email
            href: mailto:cheung.jason06@gmail.com
      - icon: github
        href: https://github.com/spiritofchaoss
        target: _blank
  page-footer: 
    background: light
    left: © Copyright 2024, Jason Cheung
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.css
    mainfont: Nunito
    toc: true